# Welcome to Jekyll!
#

# Site settings
title: WebMan Amplifier
description: Amplifies functionality of WP themes. Provides custom post types, shortcodes, metaboxes, icons.
owner: Oliver Juhas, WebMan Design # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "/webman-amplifier" # the subpath of your site, e.g. /blog
url: "https://webmandesign.github.io/webman-amplifier" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/webmandesigneu
  github: https://github.com/webmandesign
  facebook-official: https://facebook.com/webmandesigneu
  wordpress: https://wordpress.org/plugins/webman-amplifier/
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
